//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Ticket_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Login
    {
        public int Admin_Code { get; set; }
        public string Admin_userName { get; set; }
        public string Admin_pass { get; set; }
    }
}
