//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Ticket_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fare_S
    {
        public int SequenceNo { get; set; }
        public Nullable<int> Train_id { get; set; }
        public Nullable<decimal> First_ACf { get; set; }
        public Nullable<decimal> Second_ACf { get; set; }
        public Nullable<decimal> Sleeperf { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
