//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Ticket_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booked_Tickets
    {
        public decimal Ticket_Id { get; set; }
        public Nullable<int> Train_no { get; set; }
        public string Class { get; set; }
        public string Passenger_Name { get; set; }
        public string Gender { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
