//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Ticket_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation_Data
    {
        public int Canc_ID { get; set; }
        public Nullable<int> Train_no { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<System.DateTime> Canc_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Refund_Amount { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
