//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Ticket_Booking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Railway_reservationEntities1 : DbContext
    {
        public Railway_reservationEntities1()
            : base("name=Railway_reservationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Login> Admin_Login { get; set; }
        public virtual DbSet<Booked_Tickets> Booked_Tickets { get; set; }
        public virtual DbSet<Cancellation_Data> Cancellation_Data { get; set; }
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<user_login> user_login { get; set; }
        public virtual DbSet<Available_Seats> Available_Seats { get; set; }
        public virtual DbSet<Fare_S> Fare_S { get; set; }
    
        public virtual int Add_FairDet(Nullable<decimal> train_id, Nullable<int> facf, Nullable<int> sacf, Nullable<int> tacf)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("train_id", train_id) :
                new ObjectParameter("train_id", typeof(decimal));
    
            var facfParameter = facf.HasValue ?
                new ObjectParameter("facf", facf) :
                new ObjectParameter("facf", typeof(int));
    
            var sacfParameter = sacf.HasValue ?
                new ObjectParameter("sacf", sacf) :
                new ObjectParameter("sacf", typeof(int));
    
            var tacfParameter = tacf.HasValue ?
                new ObjectParameter("tacf", tacf) :
                new ObjectParameter("tacf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_FairDet", train_idParameter, facfParameter, sacfParameter, tacfParameter);
        }
    
        public virtual int Add_Seatdet(Nullable<decimal> trainid, Nullable<int> fac, Nullable<int> sac, Nullable<int> tac)
        {
            var trainidParameter = trainid.HasValue ?
                new ObjectParameter("trainid", trainid) :
                new ObjectParameter("trainid", typeof(decimal));
    
            var facParameter = fac.HasValue ?
                new ObjectParameter("fac", fac) :
                new ObjectParameter("fac", typeof(int));
    
            var sacParameter = sac.HasValue ?
                new ObjectParameter("sac", sac) :
                new ObjectParameter("sac", typeof(int));
    
            var tacParameter = tac.HasValue ?
                new ObjectParameter("tac", tac) :
                new ObjectParameter("tac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Seatdet", trainidParameter, facParameter, sacParameter, tacParameter);
        }
    
        public virtual int AddSeat(Nullable<int> trainNo, string class1)
        {
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("trainNo", trainNo) :
                new ObjectParameter("trainNo", typeof(int));
    
            var class1Parameter = class1 != null ?
                new ObjectParameter("class1", class1) :
                new ObjectParameter("class1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSeat", trainNoParameter, class1Parameter);
        }
    
        public virtual int RemoveSeat(Nullable<int> trainNo, string class1)
        {
            var trainNoParameter = trainNo.HasValue ?
                new ObjectParameter("trainNo", trainNo) :
                new ObjectParameter("trainNo", typeof(int));
    
            var class1Parameter = class1 != null ?
                new ObjectParameter("class1", class1) :
                new ObjectParameter("class1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveSeat", trainNoParameter, class1Parameter);
        }
    
        public virtual int Add_Fair(Nullable<decimal> train_id, Nullable<int> facf, Nullable<int> sacf, Nullable<int> tacf)
        {
            var train_idParameter = train_id.HasValue ?
                new ObjectParameter("train_id", train_id) :
                new ObjectParameter("train_id", typeof(decimal));
    
            var facfParameter = facf.HasValue ?
                new ObjectParameter("facf", facf) :
                new ObjectParameter("facf", typeof(int));
    
            var sacfParameter = sacf.HasValue ?
                new ObjectParameter("sacf", sacf) :
                new ObjectParameter("sacf", typeof(int));
    
            var tacfParameter = tacf.HasValue ?
                new ObjectParameter("tacf", tacf) :
                new ObjectParameter("tacf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Fair", train_idParameter, facfParameter, sacfParameter, tacfParameter);
        }
    
        public virtual int Add_Seat(Nullable<decimal> trainid, Nullable<int> fac, Nullable<int> sac, Nullable<int> tac)
        {
            var trainidParameter = trainid.HasValue ?
                new ObjectParameter("trainid", trainid) :
                new ObjectParameter("trainid", typeof(decimal));
    
            var facParameter = fac.HasValue ?
                new ObjectParameter("fac", fac) :
                new ObjectParameter("fac", typeof(int));
    
            var sacParameter = sac.HasValue ?
                new ObjectParameter("sac", sac) :
                new ObjectParameter("sac", typeof(int));
    
            var tacParameter = tac.HasValue ?
                new ObjectParameter("tac", tac) :
                new ObjectParameter("tac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Seat", trainidParameter, facParameter, sacParameter, tacParameter);
        }
    }
}
