//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Assessment_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<decimal> emp_salary { get; set; }
    }
}
